id: I63350D9A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:12:43+00:00'
last_modified: '2022-06-08T10:11:18.544026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1721
  title: 'འབྲི་གུང་ཐེལ་ཆོས་བདུད་རྩིའི་ཐིགས་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7CED:
      image_group_id: I1KG6127
      title: ''
      total_pages: 557
      order: 1
      base_file: 7CED.txt
    C37B:
      image_group_id: I1KG6128
      title: ''
      total_pages: 551
      order: 2
      base_file: C37B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
